### ISSUE TITLE
All covariates need to be in the SpatialPolygons BAU object

### ISSUE THREAD

**Issue by sue-shine** [cran/FRK#1]
Excuse me,  when I ran the function I met a problem.
BAUs4 <- auto_BAUs(manifold = STplane(), 
                   type = "grid", 
                   data = sch_obs4, 
                   cellsize = c(0.1,0.1,1), 
                   nonconvex_hull = FALSE,
                   convex = 0, 
                   tunit = "days") "
BAUs4$fs = 1 
sigma2_eps4<- fit_results_sch4$IDEmodel$get("sigma2_eps")
sch_obs4$std <- sqrt(sigma2_eps1)

S4 <- FRK(f = p ~ humi+sun+LSTNight,
          BAUs = BAUs4,
          data = list(sch_obs4), 
          basis = G4,  
          n_EM = 2,  
          tol = 0.01)  
##Error in .check_args_wrapper(f = f, data = data, basis = basis, BAUs = BAUs,  : 
  All covariates need to be in the SpatialPolygons BAU object.
How do I put the variables in? real need help, thank you for your time!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by sue-shine** [comment]
Sorry, I can't find any help in DESCRIPTION file.
The reproducible example didn't include variables, but I wanted to add some variables to the data I analyzed.

**Comment by gaborcsardi** [comment]
See here: https://github.com/cran/FRK/blob/master/DESCRIPTION#L20

**Comment by sue-shine** [comment]
Yes, I have, but I'm afraid it doesn't solve my problem

**Comment by gaborcsardi** [comment]
You need to report your issues there, i.e. at http://github.com/andrewzm/FRK/issues
The package authors don't read your reports here, this is a read only mirror of their package.

**Comment by sue-shine** [comment]
Oh thank you
